name       : gnome-icon-theme-symbolic
version    : 3.12.0
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-icon-theme-symbolic/3.12/gnome-icon-theme-symbolic-3.12.0.tar.xz : 851a4c9d8e8cb0000c9e5e78259ab8b8e67c5334e4250ebcc8dfdaa33520068b
homepage   : http://www.gnome.org
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : Symbolic icon theme for GNOME
description: |
    The GNOME Icon Theme Symbolic package contains symbolic icons for the default GNOME icon theme.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
patterns   :
    - /usr/*
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
