name        : gnome-icon-theme-symbolic
version     : 3.12.0
release     : 6
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-icon-theme-symbolic/3.12/gnome-icon-theme-symbolic-3.12.0.tar.xz : 851a4c9d8e8cb0000c9e5e78259ab8b8e67c5334e4250ebcc8dfdaa33520068b
homepage    : http://www.gnome.org
license     :  GPL-2.0
summary     : Symbolic icon theme for GNOME
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
patterns :
    - [ /usr/* ]
description : |
    The GNOME Icon Theme Symbolic package contains symbolic icons for the default GNOME icon theme.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
